image: jruby:9.1

pipelines:
  default:
    - step:
        caches:
          - bundler
        script:
          - bundle install
  tags:
    '*':
      - step:
          caches:
            - bundler
          script:
            - bundle install
            - gem build logstash-input-nats_streaming.gemspec
            - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@$( ls -1 ./logstash-input-nats_streaming-*.gem | head -1)

definitions:
  caches:
    bundler: ./vendor
